pipeline {
    agent any
    parameters {
          string(defaultValue: 'dev', description: 'Enter the name of Enviornment: dev/prod', name: 'ENV')
    }

    stages {
        stage ('Terraform init') {
            steps {

                sh "terraform init"                
            
            }
       } 

        stage ('Terraform plan') {
            steps {

                sh "terraform plan"                
            
            }
       } 

        stage ('Terraform apply') {
            steps {
                sh "echo 'yes' | terraform apply"
            }
       }
    }
    
}
